replicaCount: 1

image:
  repository: ghcr.io/${GITHUB_REPOSITORY_OWNER}/alkfejl-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

mongo:
  enabled: true
  image: mongo:6.0
  port: 27017
  persistence:
    enabled: true
    size: 1Gi
